export const SET_LOADING = "SET_LOADING";
export const SET_QUIZ = "SET_QUIZ";
export const SET_QUESTION_TYPE = "SET_QUESTION_TYPE";
export const BUILD_QUERY = "BUILD_QUERY";
export const BUILD_QUIZ_QUESTION = "BUILD_QUIZ_QUESTION";
